using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Pow.Api.Data;
using Pow.Domain.Entities;
using System.Text.Json;

namespace Pow.Api.Controllers.Auth;

/// <summary>
/// GitHub OAuth authentication controller.
/// Generated by Diana Integration: github-oauth v2.0.0
/// </summary>
[ApiController]
[Route("api/auth/github")]
public class GitHubAuthController : ControllerBase
{
    private readonly AppDbContext _db;
    private readonly IConfiguration _config;
    private readonly HttpClient _httpClient;
    private readonly ILogger<GitHubAuthController> _logger;

    public GitHubAuthController(
        AppDbContext db,
        IConfiguration config,
        IHttpClientFactory httpClientFactory,
        ILogger<GitHubAuthController> logger)
    {
        _db = db;
        _config = config;
        _httpClient = httpClientFactory.CreateClient();
        _logger = logger;
    }

    /// <summary>
    /// Get GitHub OAuth authorization URL
    /// </summary>
    [HttpGet("url")]
    public ActionResult<GitHubUrlResponse> GetGitHubAuthUrl()
    {
        var clientId = _config["GitHub:ClientId"];
        if (string.IsNullOrEmpty(clientId))
        {
            _logger.LogWarning("GitHub OAuth not configured - missing ClientId");
            return BadRequest(new { error = "GitHub OAuth not configured" });
        }

        var redirectUri = _config["GitHub:RedirectUri"] ?? "https://localhost:7296/github-callback";
        var scope = "user:email,read:user";

        var url = $"https://github.com/login/oauth/authorize?client_id={clientId}&redirect_uri={Uri.EscapeDataString(redirectUri)}&scope={scope}";

        return Ok(new GitHubUrlResponse(url));
    }

    /// <summary>
    /// Exchange OAuth code for access token and authenticate user
    /// </summary>
    [HttpPost("callback")]
    public async Task<ActionResult<GitHubAuthResponse>> GitHubCallback([FromBody] GitHubCallbackRequest request)
    {
        var clientId = _config["GitHub:ClientId"];
        var clientSecret = _config["GitHub:ClientSecret"];

        if (string.IsNullOrEmpty(clientId) || string.IsNullOrEmpty(clientSecret))
        {
            _logger.LogWarning("GitHub OAuth not configured - missing credentials");
            return BadRequest(new GitHubAuthResponse(Guid.Empty, "", false, "GitHub OAuth not configured"));
        }

        try
        {
            // 1. Exchange code for access token
            var accessToken = await ExchangeCodeForTokenAsync(clientId, clientSecret, request.Code);
            if (string.IsNullOrEmpty(accessToken))
                return BadRequest(new GitHubAuthResponse(Guid.Empty, "", false, "Failed to get access token"));

            // 2. Get user info from GitHub
            var (githubId, username, email, avatarUrl) = await GetGitHubUserInfoAsync(accessToken);

            // 3. Find or create user
            var user = await FindOrCreateUserAsync(githubId, username, email, avatarUrl, accessToken);

            _logger.LogInformation("GitHub OAuth successful for user {Email} (GitHub: {Username})", user.Email, username);

            return Ok(new GitHubAuthResponse(user.Id, user.Email, true, null));
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "GitHub OAuth callback failed");
            return BadRequest(new GitHubAuthResponse(Guid.Empty, "", false, ex.Message));
        }
    }

    private async Task<string?> ExchangeCodeForTokenAsync(string clientId, string clientSecret, string code)
    {
        var tokenRequest = new HttpRequestMessage(HttpMethod.Post, "https://github.com/login/oauth/access_token");
        tokenRequest.Headers.Accept.Add(new System.Net.Http.Headers.MediaTypeWithQualityHeaderValue("application/json"));
        tokenRequest.Content = new FormUrlEncodedContent(new Dictionary<string, string>
        {
            ["client_id"] = clientId,
            ["client_secret"] = clientSecret,
            ["code"] = code
        });

        var response = await _httpClient.SendAsync(tokenRequest);
        var json = await response.Content.ReadAsStringAsync();
        var data = JsonSerializer.Deserialize<JsonElement>(json);

        return data.TryGetProperty("access_token", out var token) ? token.GetString() : null;
    }

    private async Task<(string Id, string Username, string Email, string? AvatarUrl)> GetGitHubUserInfoAsync(string accessToken)
    {
        // Get user profile
        var userRequest = new HttpRequestMessage(HttpMethod.Get, "https://api.github.com/user");
        userRequest.Headers.Authorization = new System.Net.Http.Headers.AuthenticationHeaderValue("Bearer", accessToken);
        userRequest.Headers.UserAgent.ParseAdd("Pow-App");

        var userResponse = await _httpClient.SendAsync(userRequest);
        var userData = JsonSerializer.Deserialize<JsonElement>(await userResponse.Content.ReadAsStringAsync());

        var githubId = userData.GetProperty("id").GetInt64().ToString();
        var username = userData.GetProperty("login").GetString()!;
        var avatarUrl = userData.TryGetProperty("avatar_url", out var avatar) ? avatar.GetString() : null;

        // Get email (may need to fetch from /user/emails if private)
        var email = userData.TryGetProperty("email", out var emailProp) && emailProp.ValueKind != JsonValueKind.Null
            ? emailProp.GetString()
            : await GetPrimaryEmailAsync(accessToken);

        return (githubId, username, email ?? $"{username}@github.local", avatarUrl);
    }

    private async Task<string?> GetPrimaryEmailAsync(string accessToken)
    {
        var emailRequest = new HttpRequestMessage(HttpMethod.Get, "https://api.github.com/user/emails");
        emailRequest.Headers.Authorization = new System.Net.Http.Headers.AuthenticationHeaderValue("Bearer", accessToken);
        emailRequest.Headers.UserAgent.ParseAdd("Pow-App");

        var response = await _httpClient.SendAsync(emailRequest);
        var emails = JsonSerializer.Deserialize<JsonElement>(await response.Content.ReadAsStringAsync());

        foreach (var e in emails.EnumerateArray())
        {
            if (e.TryGetProperty("primary", out var primary) && primary.GetBoolean())
            {
                return e.GetProperty("email").GetString();
            }
        }

        return null;
    }

    private async Task<User> FindOrCreateUserAsync(string githubId, string username, string email, string? avatarUrl, string accessToken)
    {
        // Try to find by GitHub ID
        var user = await _db.Users.FirstOrDefaultAsync(u => u.GitHubId == githubId);

        if (user == null)
        {
            // Try to find by email to link accounts
            user = await _db.Users.FirstOrDefaultAsync(u => u.Email == email);

            if (user != null)
            {
                // Link GitHub to existing account
                user.GitHubId = githubId;
                user.GitHubUsername = username;
                user.GitHubAccessToken = accessToken;
                user.GitHubAvatarUrl = avatarUrl;
                _logger.LogInformation("Linked GitHub account {Username} to existing user {Email}", username, email);
            }
            else
            {
                // Create new user
                user = new User
                {
                    Id = Guid.NewGuid(),
                    Email = email,
                    PasswordHash = "", // No password for OAuth users
                    GitHubId = githubId,
                    GitHubUsername = username,
                    GitHubAccessToken = accessToken,
                    GitHubAvatarUrl = avatarUrl
                };
                _db.Users.Add(user);
                _logger.LogInformation("Created new user from GitHub: {Email} ({Username})", email, username);
            }
        }
        else
        {
            // Update existing GitHub user
            user.GitHubUsername = username;
            user.GitHubAccessToken = accessToken;
            user.GitHubAvatarUrl = avatarUrl;
        }

        await _db.SaveChangesAsync();
        return user;
    }
}

// DTOs
public record GitHubUrlResponse(string Url);
public record GitHubCallbackRequest(string Code);
public record GitHubAuthResponse(Guid UserId, string Email, bool Success, string? Error);
