/*
 * GitHub OAuth API Methods
 * Generated by Diana Integration: github-oauth v2.0.0
 *
 * This partial class extends ApiService with GitHub OAuth methods.
 */
using System.Net.Http.Json;

namespace Pow.Web.Services;

public partial class ApiService
{
    /// <summary>
    /// Get GitHub OAuth authorization URL
    /// </summary>
    public async Task<string?> GetGitHubAuthUrlAsync()
    {
        try
        {
            var response = await _http.GetFromJsonAsync<GitHubUrlResponse>("api/auth/github/url");
            return response?.Url;
        }
        catch (Exception ex)
        {
            Console.WriteLine($"Error getting GitHub auth URL: {ex.Message}");
            return null;
        }
    }

    /// <summary>
    /// Exchange GitHub OAuth code for user authentication
    /// </summary>
    public async Task<GitHubAuthResult?> GitHubCallbackAsync(string code)
    {
        try
        {
            var response = await _http.PostAsJsonAsync("api/auth/github/callback", new GitHubCallbackRequest(code));

            if (!response.IsSuccessStatusCode)
            {
                var error = await response.Content.ReadAsStringAsync();
                Console.WriteLine($"GitHub callback failed: {response.StatusCode} - {error}");
                return new GitHubAuthResult(Guid.Empty, "", false, "Authentication failed");
            }

            return await response.Content.ReadFromJsonAsync<GitHubAuthResult>();
        }
        catch (Exception ex)
        {
            Console.WriteLine($"Error in GitHub callback: {ex.Message}");
            return new GitHubAuthResult(Guid.Empty, "", false, ex.Message);
        }
    }
}

// GitHub OAuth DTOs
public record GitHubUrlResponse(string Url);
public record GitHubCallbackRequest(string Code);
public record GitHubAuthResult(Guid UserId, string Email, bool Success, string? Error);
