/*
 * GitHub OAuth User Fields
 * Generated by Diana Integration: github-oauth v2.0.0
 *
 * This partial class extends the User entity with GitHub OAuth fields.
 * Requires the base User class to be declared as 'partial'.
 */
namespace Pow.Domain.Entities;

public partial class User
{
    // ══════════════════════════════════════════════════════════════════
    // GitHub OAuth Fields
    // ══════════════════════════════════════════════════════════════════

    /// <summary>
    /// GitHub user ID (numeric, stored as string)
    /// </summary>
    public string? GitHubId { get; set; }

    /// <summary>
    /// GitHub username (login)
    /// </summary>
    public string? GitHubUsername { get; set; }

    /// <summary>
    /// GitHub OAuth access token for API calls
    /// </summary>
    public string? GitHubAccessToken { get; set; }

    /// <summary>
    /// GitHub avatar URL
    /// </summary>
    public string? GitHubAvatarUrl { get; set; }

    // ══════════════════════════════════════════════════════════════════
    // Helper Properties
    // ══════════════════════════════════════════════════════════════════

    /// <summary>
    /// Check if user has linked their GitHub account
    /// </summary>
    public bool HasGitHubLinked => !string.IsNullOrEmpty(GitHubId);

    /// <summary>
    /// Get display name (GitHub username or email)
    /// </summary>
    public string GitHubDisplayName => GitHubUsername ?? Email;
}
